parent=keycloak
import=common/keycloak

logo=img/logo.svg
styles=css/login.css
locales=fr,en

meta=viewport==width=device-width,initial-scale=1

kcHtmlClass=dgcoop-login-pf
kcLoginClass=dgcoop-login-pf-page
kcBodyClass=dgcoop-login-body
